name = "aiworkshops-pages"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
NEXT_PUBLIC_GA_ID = "G-GRYL5EPKJZ"
NEXT_PUBLIC_ENABLE_GA_DEV = "false"
